# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-11-06 01:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='default', max_length=255),
            preserve_default=False,
        ),
    ]
